-- 19. Cho biết số lượng đề án của công ty
SELECT COUNT(MADA) AS TongSoDeAn
FROM DEAN

-- 20. Cho biết số lượng đề án do phòng 'Nghiên Cứu' chủ trì
SELECT PB.TENPHG, COUNT(MADA) AS SoLuongDeAn
FROM DEAN DA
JOIN PHONGBAN PB ON DA.PHONG = PB.MAPHG
GROUP BY PB.MAPHG, PB.TENPHG
HAVING PB.TENPHG LIKE N'Nghiên Cứu'
	
-- 21. Cho biết lương trung bình của các nữ nhân viên
SELECT PHAI, AVG(LUONG) AS Luong_trung_binh
FROM NHANVIEN
GROUP BY PHAI
HAVING PHAI LIKE N'Nữ'

-- 22. Cho biết số thân nhân của nhân viên 'Đinh Bá Tiến'
SELECT COUNT(TN.MA_NVIEN) AS N'ThanNhanCuaDinhBaTien'
FROM THANNHAN TN
JOIN NHANVIEN NV ON NV.MANV = TN.MA_NVIEN
GROUP BY TN.MA_NVIEN, NV.HONV, NV.TENNV, NV.TENLOT
HAVING NV.HONV LIKE N'Đinh' AND NV.TENLOT LIKE N'Bá' AND NV.TENNV LIKE N'Tiên'
-- Có 2 thẳng Đinh Bá Tiên :V

-- 23. Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các nhân viên tham dự đề án đó
SELECT DA.TENDEAN, SUM(PC.THOIGIAN) AS Tong_So_Gio
FROM DEAN DA, PHANCONG PC
WHERE DA.MADA = PC.MADA
GROUP BY DA.TENDEAN
-- no sql chua chuan

-- 24. Với mỗi đề án, cho biết có bao nhiêu nhân viên tham gia đề án đó
SELECT DA.TENDEAN, COUNT(NV.MANV) AS So_Luong_NV
FROM NHANVIEN NV
JOIN PHANCONG PC ON NV.MANV = PC.MA_NVIEN
JOIN CONGVIEC CV ON PC.MADA = CV.MADA
JOIN DEAN DA ON CV.MADA = DA.MADA
GROUP BY DA.TENDEAN

-- 25. Với mỗi nhân viên, cho biết họ và tên nhân viên và số lượng thân nhân của nhân viên đó.
SELECT COUNT(TN.MA_NVIEN) AS N'SL_ThanNhan', NV.HONV +' '+ NV.TENLOT +' '+ NV.TENNV AS N'HoVaTenNV'
FROM NHANVIEN NV
JOIN THANNHAN TN ON NV.MANV = TN.MA_NVIEN
GROUP BY TN.MA_NVIEN , NV.HONV, NV.TENNV, NV.TENLOT

-- 26. Với mỗi nhân viên, cho biết họ tên của nhân viên và số lượng đề án mà nhân viên đó đã tham gia.
select NV.HONV +' '+ NV.TENLOT +' '+ NV.TENNV AS N'HoVaTenNV', COUNT(PC.MA_NVIEN)
FROM NHANVIEN NV
JOIN PHANCONG PC ON NV.MANV = PC.MA_NVIEN
JOIN CONGVIEC CV ON PC.MADA = CV.MADA
JOIN DEAN DA ON CV.MADA = DA.MADA
GROUP BY PC.MA_NVIEN, NV.HONV, NV.TENNV, NV.TENLOT

-- 27. Với mỗi nhân viên, cho biết số lượng nhân viên mà nhân viên đó quản lý trực tiếp.
SELECT COUNT(NV.MANV) as 'soluongnhanvienquanly', NV.HONV +' '+ NV.TENLOT +' '+ NV.TENNV AS N'HoVaTenNVQL'
FROM NHANVIEN NV
JOIN NHANVIEN NVQL ON NV.MANV = NVQL.MA_NQL
GROUP BY NV.MANV, NV.HONV, NV.TENNV, NV.TENLOT

-- 28
SELECT NV.PHG, PB.TENPHG, AVG(NV.LUONG) as 'luongtrungbinhcuaphongban'
FROM PHONGBAN PB 
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY NV.PHG , PB.TENPHG

-- 29
SELECT NV.PHG, PB.TENPHG, AVG(NV.LUONG) as 'luongtrungbinhcuaphongban' ,COUNT(NV.MANV) as 'slnhanvien'
FROM PHONGBAN PB 
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY NV.PHG , PB.TENPHG
HAVING AVG(NV.LUONG) > 30000

-- 30
SELECT PB.TENPHG, COUNT(DA.TENDEAN) as 'soluongdean'
FROM PHONGBAN PB 
JOIN DEAN DA ON PB.MAPHG = DA.PHONG
GROUP BY PB.TENPHG

-- 31
SELECT PB.TENPHG, COUNT(DA.TENDEAN) as 'soluongdean', NV.HONV +' '+ NV.TENLOT +' '+ NV.TENNV AS N'HoVaTenTP'
FROM PHONGBAN PB 
JOIN DEAN DA ON PB.MAPHG = DA.PHONG
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
GROUP BY PB.TENPHG, PB.NG_NHANCHUC, NV.HONV, NV.TENLOT ,NV.TENNV

-- 32
SELECT PB.TENPHG, AVG(NV.LUONG), COUNT(DA.TENDEAN)
FROM PHONGBAN PB
JOIN DEAN DA ON PB.MAPHG = DA.PHONG
JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.TENPHG 
HAVING AVG(NV.LUONG) > 40000

-- 33
SELECT DDP.DIADIEM, COUNT(DA.TENDEAN) as 'soluongdean'
FROM DEAN DA
JOIN PHONGBAN PB ON DA.PHONG = PB.MAPHG
JOIN DIADIEM_PHG DDP ON PB.MAPHG = DDP.MAPHG
GROUP BY DDP.DIADIEM

-- 34
SELECT DA.TENDEAN, COUNT(CV.TEN_CONG_VIEC) as 'soluongcv'
FROM DEAN DA
JOIN CONGVIEC CV ON DA.MADA = CV.MADA
GROUP BY DA.TENDEAN

-- 35. Với mỗi công việc trong đề án có mã đề án là 30, cho biết số lượng nhân viên được phân công .
SELECT CV.TEN_CONG_VIEC, COUNT(PC.MA_NVIEN) as 'soluongnhanviendcphancong'
FROM CONGVIEC CV 
JOIN DEAN DA ON CV.MADA = DA.MADA
JOIN PHANCONG PC ON CV.MADA = PC.MADA AND CV.STT = PC.STT
GROUP BY CV.TEN_CONG_VIEC, CV.MADA
HAVING CV.MADA like 30

-- 36. Với mỗi công việc trong đề án có mã đề án là 'Dao Tao', cho biết số lượng nhân viên được phân công.
SELECT CV.TEN_CONG_VIEC, COUNT(PC.MA_NVIEN) as 'soluongnhanviendcphancong'
FROM CONGVIEC CV 
JOIN DEAN DA ON CV.MADA = DA.MADA
JOIN PHANCONG PC ON CV.MADA = PC.MADA AND CV.STT = PC.STT
GROUP BY CV.TEN_CONG_VIEC, DA.TENDEAN
HAVING DA.TENDEAN like N'Đào tạo'
